name: TRDisclosure
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - mesa
  - scipy
  - openpyxl
  - sklearn
  - statsmodels
  - seaborn

